{% set name = "prrte" %}
{% set version = "3.0.11" %}

package:
  name: {{ name|lower }}-split
  version: {{ version }}

source:
  url: https://github.com/openpmix/prrte/releases/download/v{{ version }}/prrte-{{ version }}.tar.bz2
  sha256: 37af5a82d333a54c0bac358f06c194427b7dbfa7b8b85f2ddd1145acf71cfdd4

build:
  skip: true  # [win]
  number: 1

# one top-level build
# outputs select which files to include
# from this build
# but don't run any build scripts themselves
requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib('c') }}
    - make
    - flex
    - pkg-config
    - pmix-bin
      # [target_platform != build_platform]
  host:
    - libevent
    - libhwloc
    - libpmix-devel
    - pmix-bin

outputs:
  - name: libprrte
    files:
      # libprrte has everything except for specific exclusions
      include:
        - '**/*'
      exclude:
        # these are in -bin
        - bin/
        # these are in -devel
        - include
        # exclude docs (not packaged)
        - share/prte/rst
        - share/doc/
        - share/man/
    build:
      run_exports:
        - {{ pin_subpackage('libprrte', max_pin='x') }}
    requirements:
      # only need requirements with run_exports here
      # no build is actually run
      build:
        - {{ compiler('c') }}
        - {{ stdlib('c') }}
      host:
        - libevent
        - libhwloc
        - libpmix-devel
        # not needed for run exports
        # but pcc symlink is removed if not here
        - pmix-bin

    test:
      commands:
        - test -f $PREFIX/lib/libprrte${SHLIB_EXT}
        - test ! -f $PREFIX/lib/libprrte.a
        - test ! -f $PREFIX/bin/prte_info
        - test ! -f $PREFIX/bin/prun
        - test ! -d $PREFIX/include/prte/src
        - test ! -d $PREFIX/share/doc/prte

  - name: libprrte-devel
    build:
      run_exports:
        - {{ pin_subpackage('libprrte', max_pin='x') }}
    files:
      include:
        - include
    requirements:
      run:
        - {{ pin_subpackage('libprrte', exact=True) }}
    test:
      commands:
        - test -f $PREFIX/include/prte.h
        - test -d $PREFIX/include/prte/src

  - name: prrte
    files:
      # should only include files excluded by libprrte
      include:
        - bin/
    requirements:
      build:
        - {{ compiler('c') }}
        - {{ stdlib('c') }}
      host:
        - libevent
        - libhwloc
        - libpmix-devel
        - pmix-bin
        - {{ pin_subpackage('libprrte', exact=True) }}
      run:
        - {{ pin_subpackage('libprrte', exact=True) }}
    test:
      requires:
        # only required for verifying pcc symlink
        - pmix-bin
      commands:
        - prte_info
        - prun --do-not-connect --allow-run-as-root -n 2 sh -c 'echo hi'
        - pcc -showme


about:
  home: https://prrte.org
  summary: PMIx Reference RunTime Environment
  description: |
    PRRTE is the PMIx Reference RunTime Environment
  license: BSD-3-Clause
  license_file: LICENSE
  doc_url: https://docs.prrte.org
  dev_url: https://github.com/openpmix/prrte

extra:
  feedstock-name: prrte
  recipe-maintainers:
    - j34ni
    - minrk
